FROM amd64/alpine:3.23 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/exportenv"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/exportenv /usr/bin/exportenv
